version: '3'

services:
  proxy:
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - server

  database:
    image: postgres:10.6

  server:
    build:
      ./company_employees
    image:
      empl
    command:
      bash -c 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    depends_on:
      - migrate
      - database
    volumes:
      - ./company_employees:/app
      - static:/app/static
      - media:/app/media

  migrate:
    image:
      empl
    command:
      bash -c 'python manage.py migrate'
    volumes:
    - ./company_employees:/app
    - static:/app/static
    - media:/app/media
    depends_on:
    - database

volumes:
  static:
  media: