# Generated by Django 2.1.1 on 2019-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_work',
            field=models.DateField(),
        ),
    ]
